name: Build VFS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20


      - name: Ensure package-lock exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json not found. Generating..."
            npm install --package-lock-only
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: add package-lock.json"
            git push
          else
            echo "package-lock.json exists"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build VFS
        run: node src/build-vfs.mjs

      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/vfs.js
          git diff --cached --exit-code || git commit -m "chore: regenerate vfs.js"
          git push
